Traceback (most recent call last):
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/bitzer/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib
import numpy
from matplotlib import pyplot
from myst_nb import glue

# this script only consist of plotting predifinded vectors
# and the convolution of them with the system

matplotlib.style.use('sv.mplstyle')

index = [0, 1, 2, 3, 4, 5, 6]
x = [1, 0.5, 1]
x0 = [1, 0, 0]
x1 = [0, 0.5, 0]
x2 = [0, 0, 1]
system = [0.5, 0.75, 1]

fig, ((ax_input, ax_system),(ax_x0, ax_yx0),(ax_x1, ax_yx1),(ax_x2, ax_yx2),
        (ax_empty, ax_sum)) = pyplot.subplots(5, 2, sharex='all', sharey='all')


ax_input.stem(x + [0, 0], use_line_collection=True)
ax_input.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 
        title='Inputsignal', xlim=[0, 6], ylim=[0, 2])

ax_system.stem(system + [0, 0], use_line_collection=True)
ax_system.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 
        title='System', xlim=[0, 6], ylim=[0, 2])

ax_x0.stem(x0, use_line_collection=True)
ax_x0.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 
        title='Input bei x[0]', xlim=[0, 6], ylim=[0, 2])

y_x_0 = numpy.convolve(x0, system)
ax_yx0.stem(y_x_0, use_line_collection=True)
ax_yx0.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 
        title='Systemantwort f√ºr x[0]', xlim=[0, 6], ylim=[0, 2])


ax_x1.stem(x1, use_line_collection=True)
ax_x1.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 
        title='Input bei x[1]', xlim=[0, 6], ylim=[0, 2])

y_x_1 = numpy.convolve(x1, system)
ax_yx1.stem(y_x_1, use_line_collection=True)
ax_yx1.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 
        title='Systemantwort f√ºr x[1]', xlim=[0, 6], ylim=[0, 2])


ax_x2.stem(x2, use_line_collection=True)
ax_x2.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 
        title='Input bei x[2]', xlim=[0, 6], ylim=[0, 2])

y_x_2 = numpy.convolve(x2, system)
ax_yx2.stem(y_x_2, use_line_collection=True)
ax_yx2.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 
        title='Systemantwort f√ºr x[2]', xlim=[0, 6], ylim=[0, 2])

conv_sum = numpy.convolve(input, system)
ax_sum.stem(conv_sum, use_line_collection=True)
ax_sum.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 
        title='Systemantwort f√ºr Inputsignal', xlim=[0, 6], ylim=[0, 2])

glue("FaltungErklaerung", fig, display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_180345/4222063163.py[0m in [0;36m<module>[0;34m[0m
[1;32m     57[0m         title='Systemantwort f√ºr x[2]', xlim=[0, 6], ylim=[0, 2])
[1;32m     58[0m [0;34m[0m[0m
[0;32m---> 59[0;31m [0mconv_sum[0m [0;34m=[0m [0mnumpy[0m[0;34m.[0m[0mconvolve[0m[0;34m([0m[0minput[0m[0;34m,[0m [0msystem[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     60[0m [0max_sum[0m[0;34m.[0m[0mstem[0m[0;34m([0m[0mconv_sum[0m[0;34m,[0m [0muse_line_collection[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     61[0m ax_sum.set(xlabel='Folgenindex k ->', ylabel='Amplitude x[k]', 

[0;32m<__array_function__ internals>[0m in [0;36mconvolve[0;34m(*args, **kwargs)[0m

[0;32m~/SoftDev/Python/ScienceEnv/SE/lib/python3.9/site-packages/numpy/core/numeric.py[0m in [0;36mconvolve[0;34m(a, v, mode)[0m
[1;32m    842[0m     [0;32mif[0m [0mlen[0m[0;34m([0m[0mv[0m[0;34m)[0m [0;34m==[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    843[0m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m'v cannot be empty'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 844[0;31m     [0;32mreturn[0m [0mmultiarray[0m[0;34m.[0m[0mcorrelate[0m[0;34m([0m[0ma[0m[0;34m,[0m [0mv[0m[0;34m[[0m[0;34m:[0m[0;34m:[0m[0;34m-[0m[0;36m1[0m[0;34m][0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    845[0m [0;34m[0m[0m
[1;32m    846[0m [0;34m[0m[0m

[0;31mTypeError[0m: unsupported operand type(s) for *: 'float' and 'method'
TypeError: unsupported operand type(s) for *: 'float' and 'method'

